### ISSUE TITLE
Clarify behavior of relatedResource(Collection)

### ISSUE THREAD

**Issue by ThomasWeiser** [noahzgordon/elm-jsonapi#27]
`relatedResource` and `relatedResourceCollection` return resources side-loaded in the `include` part of a compound document. The documentation should probably make a clear statement about this.

**Comment by noahzgordon** [comment]
How about a passage like the following:

JSON API specifies a format with which resources related to the document's primary resource(s) are "side-loaded" under a key called `included`. This library abstracts the structure of the document and reconstructs the resource graph for you; use the `relatedResource` and `relatedResourceCollection` functions to traverse the graph from any given resource to its related resources.

**Comment by ThomasWeiser** [comment]
Great!

**Comment by ThomasWeiser** [comment]
Settled in ad64958e480e54da9b89f21b42c8362c1d2b0b67
